apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: fastapi-backend-build-
  namespace: fastapi-cicd
spec:
  serviceAccountName: fastapi-pipeline

  taskRef:
    name: clone-build-push

  params:
    - name: repo-url
      value: https://github.com/pafful/fastapi-app.git

    - name: revision
      value: main

    - name: context-dir
      value: backend

    - name: dockerfile
      value: Dockerfile

    - name: image
      value: image-registry.openshift-image-registry.svc:5000/fastapi-app/fastapi-backend:latest